### Question:

#### We have to create an array with given conditions.

In [12]:
import numpy as np

### Code 1:

In [13]:
a = np.ones((5,5),dtype=int)

In [14]:
x = int(input("Enter the value you want fill in with 3x3 matrix:"))
y = int(input("Enter the value that you want to fill in the middle of array: "))

Enter the value you want fill in with 3x3 matrix:0
Enter the value that you want to fill in the middle of array: 9


In [15]:
a[1:4,1:4]=x
a[2,2]=y

In [17]:
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Code 2:

In [19]:
x = int(input("Enter the value of which you want to create an array: "))
y = int(input("Enter the value you want fill in with 3x3 matrix:"))
z = int(input("Enter the value that you want to fill in the middle of 3x3 matrix: "))

Enter the value of which you want to create an array: 4
Enter the value you want fill in with 3x3 matrix:0
Enter the value that you want to fill in the middle of 3x3 matrix: 9


In [36]:
a = np.full((5,5),x,dtype=int)
b = np.full((3,3),y,dtype=int)
print(a)
print(b)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [52]:
m = str(input("Choose whether you want to enter row/column index value: "))
if m=="row":
    p = int(input("Enter starting row index: "))
    a[p:p+3,0:]=y
else:
    if m=="column":
        q = int(input("Enter starting column index: "))
        a[0:,q:q+3]=y

Choose whether you want to enter row/column index value: column
Enter starting column index: 2


In [53]:
print(a)

[[4 4 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [4 4 0 0 0]]
